version: '3'
services:
    shadowsocks:
        container_name: "shadowsocks"
        image: "nyanim/shadowsocks:latest"
        ports:
         - "1984:1984"
        volumes:
         - "./shadowsocks.json:/tmp/shadowsocks.json"
        restart: always